package xyz.tesser.sdk.java;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.fasterxml.jackson.databind.JsonNode;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import xyz.tesser.sdk.java.internal.signing.Stamp;
import xyz.tesser.sdk.java.internal.signing.StampResult;
import xyz.tesser.sdk.java.internal.util.Json;

/**
 * The parity gate. Asserts the assembled activity body is byte-identical to what the Kotlin SDK
 * emits for the same inputs. Fixtures are generated by :fixtures:run; regenerate them whenever the
 * Kotlin SDK changes.
 */
class GoldenBodyParityTest {

    // Only organizationId reaches the body, so the key pair is irrelevant to the
    // comparison, but LocalSigner now derives and checks it, so it has to be real.
    private static final SigningConfig CFG = TestKeys.config("org_fixture");

    /** The generator's timestamps were normalised; match that here. */
    private static final long FIXED_TS = 1_234_567_890_123L;

    private static Stamp stubStamp() {
        Stamp stamp = mock(Stamp.class);
        when(stamp.stamp(any(), any()))
                .thenReturn(CompletableFuture.completedFuture(new StampResult("X-Stamp", "S")));
        return stamp;
    }

    private static String normalise(String body) {
        return body.replaceAll("\"timestampMs\":\"\\d+\"", "\"timestampMs\":\"<TS>\"");
    }

    private static JsonNode fixtures() throws Exception {
        try (InputStream in =
                GoldenBodyParityTest.class.getResourceAsStream("/fixtures/bodies.json")) {
            assertThat(in).as("fixtures/bodies.json on the test classpath").isNotNull();
            return Json.readTree(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        }
    }

    @TestFactory
    List<DynamicTest> createWalletBodiesMatchTheKotlinSdkByteForByte() throws Exception {
        JsonNode wallets = fixtures().get("wallets");
        Map<String, CreateWalletParams> cases =
                Map.of(
                        "eth-plain",
                                new CreateWalletParams("wallet", WalletType.STABLECOIN_ETHEREUM),
                        "sol-plain", new CreateWalletParams("wallet", WalletType.STABLECOIN_SOLANA),
                        "xlm-plain",
                                new CreateWalletParams("wallet", WalletType.STABLECOIN_STELLAR),
                        "eth-quotes",
                                new CreateWalletParams(
                                        "a \"quoted\" name", WalletType.STABLECOIN_ETHEREUM),
                        "eth-emoji",
                                new CreateWalletParams("wallet 💸", WalletType.STABLECOIN_ETHEREUM),
                        "eth-newline",
                                new CreateWalletParams(
                                        "line1\nline2", WalletType.STABLECOIN_ETHEREUM),
                        "eth-empty", new CreateWalletParams("", WalletType.STABLECOIN_ETHEREUM));

        List<DynamicTest> tests = new ArrayList<>();
        for (Map.Entry<String, CreateWalletParams> e : cases.entrySet()) {
            String expected = wallets.get(e.getKey()).asText();
            tests.add(
                    DynamicTest.dynamicTest(
                            "createWallet/" + e.getKey(),
                            () -> {
                                LocalSigner signer =
                                        new LocalSigner(CFG, stubStamp(), () -> FIXED_TS);
                                String actual =
                                        normalise(
                                                signer.signCreateWallet(e.getValue())
                                                        .get()
                                                        .metadata()
                                                        .body());
                                assertThat(actual).isEqualTo(expected);
                            }));
        }
        assertThat(tests).hasSize(7);
        return tests;
    }

    @TestFactory
    List<DynamicTest> signStepBodiesMatchTheKotlinSdkByteForByte() throws Exception {
        JsonNode steps = fixtures().get("steps");
        List<String> networks =
                List.of(
                        "BASE",
                        "BASE_SEPOLIA",
                        "ETHEREUM",
                        "ETHEREUM_SEPOLIA",
                        "POLYGON",
                        "POLYGON_AMOY",
                        "SOLANA");

        List<DynamicTest> tests = new ArrayList<>();
        for (String net : networks) {
            String expected = steps.get(net).asText();
            tests.add(
                    DynamicTest.dynamicTest(
                            "signStep/" + net,
                            () -> {
                                LocalSigner signer =
                                        new LocalSigner(CFG, stubStamp(), () -> FIXED_TS);
                                StepForSigning step =
                                        new StepForSigning(
                                                "step_abc",
                                                "reb_123",
                                                "0x02ed81893a850165a0bc",
                                                "0xb909cbe4a348754b17b474df9f12ab8842020165",
                                                net);
                                String actual =
                                        normalise(signer.signStep(step).get().metadata().body());
                                assertThat(actual).isEqualTo(expected);
                            }));
        }
        assertThat(tests).hasSize(7);
        return tests;
    }
}
