package xyz.tesser.sdk.java.internal.util;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * The signature is base64 of exact JSON text, so Jackson must reproduce
 * kotlinx.serialization's escaping byte for byte. Fixtures are generated by
 * :fixtures:run against the real Kotlin SDK's serializer.
 */
class JsonEscapingParityTest {

    @TestFactory
    List<DynamicTest> jacksonMatchesKotlinxForEveryHostileString() throws Exception {
        JsonNode fixtures;
        try (InputStream in = getClass().getResourceAsStream("/fixtures/escaping.json")) {
            assertThat(in).as("fixtures/escaping.json on the test classpath").isNotNull();
            fixtures = Json.readTree(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        }

        List<DynamicTest> tests = new ArrayList<>();
        for (Map.Entry<String, JsonNode> entry : fixtures.properties()) {
            String caseName = entry.getKey();
            String kotlinJson = entry.getValue().asText();

            tests.add(
                    DynamicTest.dynamicTest(
                            caseName,
                            () -> {
                                // Recover the raw walletName the generator used, by
                                // parsing Kotlin's own output. Round-tripping through a
                                // parser is safe; only the *writer* is under test.
                                String walletName =
                                        Json.readTree(kotlinJson).get("walletName").asText();

                                ObjectNode node = Json.newObject();
                                node.put("walletName", walletName);
                                String jacksonJson = Json.write(node);

                                assertThat(jacksonJson)
                                        .as(
                                                "case '%s': Jackson must match kotlinx byte for byte",
                                                caseName)
                                        .isEqualTo(kotlinJson);
                                assertThat(jacksonJson.getBytes(StandardCharsets.UTF_8))
                                        .isEqualTo(kotlinJson.getBytes(StandardCharsets.UTF_8));
                            }));
        }
        assertThat(tests).hasSizeGreaterThanOrEqualTo(20);
        return tests;
    }
}
